version: '3.8'

services:
  gold-backend:
    container_name: gold-backend
    build: .
    restart: unless-stopped
    ports:
      - "3023:3023"
    environment:
      NODE_ENV: production
      PORT: 3023
      DATABASE_URL: "postgresql://srmobile:P90pO89o@postgres:5432/acessos?sslmode=disable"
      DATABASE_ACESSOS: "postgresql://srmobile:P90pO89o@postgres:5432/acessos?sslmode=disable"
      DATABASE_MODELO: "postgresql://srmobile:P90pO89o@postgres:5432/goldpdv?sslmode=disable"
      TENANT_DATABASE_URL_TEMPLATE: "postgresql://srmobile:P90pO89o@postgres:5432/{{TENANT}}?sslmode=disable"
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: srmobile
      DB_PASS: P90pO89o
      DB_ENCRYPT: "false"
      DB_TRUST_SERVER_CERTIFICATE: "true"
    networks:
      - vpn_docker
         

networks:
  vpn_docker:
    external: true
    driver: bridge
